In [3]:
import numpy as np

In [4]:
a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [5]:
array1=np.array([51,52,3,54,55,56,57,58,59,60,61,62,63,64,65,6667,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99])

In [7]:
type(array1)

numpy.ndarray

In [8]:
array1 * 2

array([  102,   104,     6,   108,   110,   112,   114,   116,   118,
         120,   122,   124,   126,   128,   130, 13334,   136,   138,
         140,   142,   144,   146,   148,   150,   152,   154,   156,
         158,   160,   162,   164,   166,   168,   170,   172,   174,
         176,   178,   180,   182,   184,   186,   188,   190,   192,
         194,   196,   198])

In [9]:
array1 > 80

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [11]:
array2 = array1[array1 > 80]
print(array2)

[6667   81   82   83   84   85   86   87   88   89   90   91   92   93
   94   95   96   97   98   99]


In [13]:
array2 = array1[array1 % 2 == 0]
print(array2)

[52 54 56 58 60 62 64 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


In [15]:
score = np.loadtxt("C:\\Users\\Vaijnath Shejul\\Downloads\\download\\survey.txt", dtype = "int")

In [16]:
score = np.loadtxt("survey.txt", dtype = "int")

In [23]:
print(score.shape)
print(score.ndim)

(1167,)
1


In [24]:
score[:5]

array([ 7, 10,  5,  9,  9])

In [34]:
detractors = score[ score < 7]
print(detractors)

[5 4 4 5 1 5 5 1 4 5 4 4 4 5 1 4 1 4 1 5 5 1 1 4 1 5 4 1 1 4 1 5 1 4 4 1 1
 1 1 1 1 1 4 1 1 5 5 5 4 4 1 4 1 4 1 5 1 1 5 4 4 4 4 1 4 5 4 4 1 1 5 5 1 5
 1 5 5 4 5 4 1 1 1 1 4 1 4 4 5 4 1 1 1 1 5 4 5 5 4 1 5 1 4 4 1 1 1 4 4 5 5
 4 5 5 5 1 4 1 5 5 1 5 1 1 5 5 4 4 1 4 4 4 1 1 4 4 4 5 5 1 1 4 1 4 1 4 1 4
 1 4 1 5 4 4 5 1 4 5 5 5 1 5 4 1 1 5 5 5 4 5 4 4 1 4 4 4 4 5 1 5 5 1 4 4 5
 1 1 4 5 5 5 1 4 5 5 4 1 5 5 5 1 1 5 5 1 1 1 4 5 5 4 4 4 5 1 4 1 4 5 4 5 5
 1 5 1 5 5 1 4 5 5 4 1 5 1 4 1 4 1 1 1 1 1 1 4 1 5 4 5 1 5 1 5 4 4 4 4 5 5
 1 4 1 5 5 1 4 1 1 4 4 4 4 1 4 1 1 4 1 5 4 1 1 5 4 5 4 4 4 1 5 5 1 4 5 4 4
 4 1 4 1 4 4 4 5 1 1 1 4 5 5 1 5 4 5 5 4 1 1 5 5 5 1 4 5 4 5 5 5 1 4 1 5]


In [27]:
num_detractors = len(detractors)
print(num_detractors)

332


In [28]:
total = len(score)

In [30]:
perc_detractors = num_detractors/total
print(perc_detractors)

0.28449014567266495


In [36]:
promoters = score[ score > 8]
num_promoters = len(promoters)
print(promoters)

[10  9  9  9  9  9 10  9  9 10  9  9  9  9  9  9  9 10 10  9 10  9 10  9
  9 10 10  9 10  9 10 10 10  9  9 10 10 10  9 10  9 10  9  9  9 10  9  9
  9  9  9  9 10  9  9  9 10  9 10  9  9  9  9  9 10 10  9 10  9  9 10  9
  9 10  9  9  9  9  9  9  9  9  9  9  9 10  9  9  9  9  9  9  9  9 10  9
  9  9  9  9 10 10  9 10 10 10 10  9 10  9  9  9  9  9  9  9 10  9 10  9
 10  9 10 10 10  9  9 10 10  9  9  9  9 10  9  9  9  9 10 10  9  9  9 10
  9  9  9  9  9 10  9  9  9 10  9 10 10  9  9  9  9 10  9 10  9  9  9  9
 10  9 10  9  9  9  9  9  9  9  9  9  9  9 10 10  9  9  9 10  9 10 10 10
 10 10  9  9  9  9 10 10 10  9  9 10  9 10 10 10 10  9 10 10  9 10  9  9
  9  9 10  9 10  9 10  9  9  9  9 10  9  9  9  9  9 10  9 10 10  9 10 10
 10  9  9  9  9  9  9 10  9  9 10  9 10 10  9  9  9 10 10 10 10  9  9  9
 10 10  9 10  9  9  9 10  9  9  9  9  9  9  9  9  9  9 10  9  9  9 10  9
 10  9 10  9 10  9  9 10 10  9  9  9 10  9  9 10  9  9  9  9  9  9 10 10
  9 10  9  9  9  9 10  9  9  9  9 10  9 10  9 10  9

In [39]:
perc_promoters = num_promoters/total
print(perc_promoters)

0.5218508997429306


In [40]:
nps = perc_promoters - perc_detractors
print(nps)

0.2373607540702657


In [41]:
score.min()

1

In [42]:
score.max()

10

In [44]:
ans = np.round(nps, 2)
print(ans)

0.24


In [45]:
data = np.loadtxt("fit.txt", dtype = 'str')

In [46]:
print(data)

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']
 ['11-10-2017' '4545' 'Sad' '149' '6' 'Inactive']
 ['12-10-2017' '4340' 'Sad' '140' '6' 'Inactive']
 ['13-10-2017' '1230' 'Sad' '38' '7' 'Inactive']
 ['14-10-2017' '61' 'Sad' '1' '5' 'Inactive']
 ['15-10-2017' '1258' 'Sad' '40' '6' 'Inactive']
 ['16-10-2017' '3148' 'Sad' '101' '8' 'Inactive']
 ['17-10-2017' '4687' 'Sad' '152' '5' 'Inactive']
 ['18-10-2017' '4732' 'Happy' '150' '6' 'Active']
 ['19-10-2017' '3519' 'Sad' '113' '7' 'Inactive']
 ['20-10-2017' '1580' 'Sad' '49' '5' 'Inactive']
 ['21-10-2017' '2822' 'Sad' '86' '6' 'Inactive']
 ['22-10-2017' '181' 'Sad' '6' '8' 'Inactive']
 ['23-10-2017' '3158' 'Neutral' '99' '5' 'Inactive']
 ['24-10-2017' '4383' 'Neutral' '143' '4' 'Inactive']
 ['25-10-2017' '3881' 'Neutral' '125' '5' 'Inactive'

In [47]:
data.ndim

2

In [48]:
data.shape

(96, 6)

In [49]:
data[1]

array(['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'], dtype='<U10')

In [50]:
print(data[:5])

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']]


In [51]:
data_t = data.T #Transose
print(data_t)

[['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
  '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
  '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
  '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
  '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
  '31-10-2017' '01-11-2017' '02-11-2017' '03-11-2017' '04-11-2017'
  '05-11-2017' '06-11-2017' '07-11-2017' '08-11-2017' '09-11-2017'
  '10-11-2017' '11-11-2017' '12-11-2017' '13-11-2017' '14-11-2017'
  '15-11-2017' '16-11-2017' '17-11-2017' '18-11-2017' '19-11-2017'
  '20-11-2017' '21-11-2017' '22-11-2017' '23-11-2017' '24-11-2017'
  '25-11-2017' '26-11-2017' '27-11-2017' '28-11-2017' '29-11-2017'
  '30-11-2017' '01-12-2017' '02-12-2017' '03-12-2017' '04-12-2017'
  '05-12-2017' '06-12-2017' '07-12-2017' '08-12-2017' '09-12-2017'
  '10-12-2017' '11-12-2017' '12-12-2017' '13-12-2017' '14-12-2017'
  '15-12-2017' '16-12-2017' '17-12-2017' '18-12-2017' '19-12-2

In [52]:
data_t.shape

(6, 96)

In [54]:
dates = data_t[0]
print(dates)

['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
 '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
 '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
 '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
 '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
 '31-10-2017' '01-11-2017' '02-11-2017' '03-11-2017' '04-11-2017'
 '05-11-2017' '06-11-2017' '07-11-2017' '08-11-2017' '09-11-2017'
 '10-11-2017' '11-11-2017' '12-11-2017' '13-11-2017' '14-11-2017'
 '15-11-2017' '16-11-2017' '17-11-2017' '18-11-2017' '19-11-2017'
 '20-11-2017' '21-11-2017' '22-11-2017' '23-11-2017' '24-11-2017'
 '25-11-2017' '26-11-2017' '27-11-2017' '28-11-2017' '29-11-2017'
 '30-11-2017' '01-12-2017' '02-12-2017' '03-12-2017' '04-12-2017'
 '05-12-2017' '06-12-2017' '07-12-2017' '08-12-2017' '09-12-2017'
 '10-12-2017' '11-12-2017' '12-12-2017' '13-12-2017' '14-12-2017'
 '15-12-2017' '16-12-2017' '17-12-2017' '18-12-2017' '19-12-2017'
 '20-12-20

In [55]:
step_count = data_t[1]
print(step_count)

['5464' '6041' '25' '5461' '6915' '4545' '4340' '1230' '61' '1258' '3148'
 '4687' '4732' '3519' '1580' '2822' '181' '3158' '4383' '3881' '4037'
 '202' '292' '330' '2209' '4550' '4435' '4779' '1831' '2255' '539' '5464'
 '6041' '4068' '4683' '4033' '6314' '614' '3149' '4005' '4880' '4136'
 '705' '570' '269' '4275' '5999' '4421' '6930' '5195' '546' '493' '995'
 '1163' '6676' '3608' '774' '1421' '4064' '2725' '5934' '1867' '3721'
 '2374' '2909' '1648' '799' '7102' '3941' '7422' '437' '1231' '1696'
 '4921' '221' '6500' '3575' '4061' '651' '753' '518' '5537' '4108' '5376'
 '3066' '177' '36' '299' '1447' '2599' '702' '133' '153' '500' '2127'
 '2203']


In [62]:
print(max(step_count))
print(min(step_count))

995
1163
